config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create, :destroy]
    resources :reviews, only: [:index, :create]
  end

  resources :users, only: [:show]

  get '/profile', to: 'users#profile', as: 'user_profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :reviews, through: :product

  validate :booking_dates_available

  def booking_dates_available
    if product.bookings.where("start_date <= ? AND end_date >= ?", end_date, start_date).any?
      errors.add(:base, "Dates not available")
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  attribute :product_type, :string

  def booked_for?(user)
    bookings.where(user: user).exists?
  end

  def average_rating
    reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  belongs_to :product

  # validate :review_after_booking_end_date

  # def review_after_booking_end_date
  #   if booking && created_at < booking.end_date
  #     errors.add(:created_at, "must be after booking end date")
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :products
  has_one_attached :photo
  # validates :phone_number, presence: true, format: { with: /\\A\\+351\\s9\\d{8}\\z/, message: "must be in the format +351 9xxxxxxxx" }
  validates :city, :district, :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :phone_number, :city, :district, :country])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :phone_number, :city, :district, :country])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @booking = @product.bookings.build(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to user_path(current_user), notice: 'Booking was successfully created.'
    else
      redirect_to @product
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user), notice: 'Booking was successfully cancelled.'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @products = Product.all
    @products = [] if @products.nil?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @products = Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    elsif params[:product_type]
      @products = Product.where(product_type: params[:product_type])
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
    @bookings = @product.bookings.where("start_date >= ?", Date.today)
    @review = Review.new
    @booking = Booking.new

    if params[:start_date].present? && params[:end_date].present?
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])
      @bookings = @bookings.where.not("start_date < ? AND end_date > ?", end_date, start_date)
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    # Upload photo to Cloudinary
    result = Cloudinary::Uploader.upload(params[:product][:photo])
    @product.photo_public_id = result['public_id']

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end


  def edit
    if current_user != @product.user
      redirect_to @product, alert: "You can only edit your own products."
    end
  end

  def update
    if current_user == @product.user && @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    if current_user == @product.user
      @product.destroy
      redirect_to user_path(current_user), notice: "Product was successfully destroyed."
    else
      redirect_to @product, alert: "You can only delete your own products."
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :product_type, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @booking = Booking.find_by(user: current_user, product: @product)
    if @booking.present?
      @review = @booking.reviews.build(review_params)
      @review.booking = @booking
      @review.user = current_user
      @review.product = @product
      if @review.save
        redirect_to product_path(@product)
      else
        redirect_to product_path(@product), alert: "You need to book this product before you can review it."
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:product_id, :rating, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if params[:id] == "sign_out"
      sign_out current_user
      redirect_to root_path
    else
      @user = User.find(params[:id])
      @listings = @user.products
      @bookings = Booking.where(user: current_user)
      redirect_to root_path, alert: "User not found" if @user.nil?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @booking.product.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user.email %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @booking.end_date %>
</p>

<% if @booking.start_date > Date.today %>
  <p>Status: Booked</p>
<% elsif @booking.start_date <= Date.today && Date.today <= @booking.end_date %>
  <p>Status: Ongoing</p>
<% elsif @booking.end_date == Date.today %>
  <p>Status: Finished</p>
<% end %>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', @booking.product %>

app/views/pages/home.html.erb
        <main class="main">
            <!--=============== HOME ===============-->
            <section class="home section" id="home">
                <div class="home__container container grid">
                    <div>
                        <img src="https://cdn.shopify.com/s/files/1/0250/9779/7729/t/19/assets/Rampage-stealth-2.png?v=41014001996176970981666039374">
                    </div>

                    <div class="home__data">
                        <div class="home__header">
                            <h1 class="home__title">Share</h1>
                            <h2 class="home__subtitle">Gaming Gear</h2>
                        </div>

                        <div class="home__footer">
                            <h3 class="home__title-description">Level up your game!</h3>
                            <p class="home__description">Gamify is a unlocks the power of lending games and consoles marketplace app. Access our vast librar conveniently, while trading with fellow gamers.
                            </p>
                            <%= link_to products_path , class: "button button--flex" do %>
                              <span class="button--flex">
                                  <i class="ri-shopping-bag-line button__icon"></i> See Listings
                              </span>
                              <% end %>
                        </div>
                    </div>
                </div>
            </section>

            <!--=============== SPONSOR ===============-->
            <section class="sponsor section">
            <section class="products section" id="products">
            <h2 class="section__title section__title-gradient products__line">
                    Sponsors
                </h2>
                </section>
                <div class="sponsor__container container grid">

                    <a href="https://apple.com" target="_blank"><img src="https://i.imgur.com/3XIyl0y.png" alt="Apple Sponsor" class="sponsor__img"></a>
                    <a href="https://lewagon.com" target="_blank"><img src="https://i.imgur.com/bOx3906.png" alt="Le Wagon Sponsor" class="sponsor__img"></a>
                    <a href="https://twitch.tv" target="_blank"><img src="https://i.imgur.com/4EjGiju.png" alt="Twitch Sponsor" class="sponsor__img"></a>
                    <a href="https://github.com" target="_blank"><img src="https://i.imgur.com/1Amfqsy.png" alt="Github Sponsor" class="sponsor__img"></a>
                    <a href="https://youtube.com" target="_blank"><img src="https://i.imgur.com/yQd1kf9.png" alt="Youtube Sponsor" class="sponsor__img"></a>
                </div>
            </section>

            <!--=============== CASE ===============-->

            <!--=============== DISCOUNT ===============-->
            <section class="discount section" id="Signin">
                <div class="discount__container container grid">
                    <div class="discount__animate">
                        <h2 class="discount__title">Immerse yourself in <br> the world of gaming</h2>
                        <p class="discount__description">Share the fun, lend and borrow your favorite games</p>
                        <%= link_to  new_user_registration_path , class: "button button--flex"  do %>
                            <i class="ri-shopping-bag-line button__icon"></i> Sign up
                        <% end %>
                    </div>

                    <img src="https://gmedia.playstation.com/is/image/SIEPDC/PSVR2-thumbnail-01-en-22feb22?$facebook$" alt="" class="discount__img">
                </div>
            </section>




            <!--=============== PRODUCTS ===============-->
          <div class="product-section">
            <div class="search-section">

            </div>
            <section class="products section" id="products">
                <h2 class="section__title section__title-gradient products__line">
                    Step up <br> your Game
                </h2>
                <div class="footer__content" id="searchbar">
                  <%= form_tag products_path, :method => 'get', class: "footer__form" do %>
                    <%= text_field_tag :search, params[:search], class: "footer__input", placeholder: "  Search Products" %>
                    <%= submit_tag "Search", class: 'button button--flex' %>
                  <% end %>
                <div class="products__container container grid">
                    <% @products[0...9].each do |product| %>
                      <article class="products__card">
                        <div class="products__content">
                          <%= link_to product_path(product) do %>
                            <%= cl_image_tag product.photo.key, width: 400, height: 300,crop: :pad, class:"card-img-top; products__img", alt:"Product image", id: "user_prodc" %>
                          <% end %>
                          <h3 class="products__title"><%= product.name %></h3>
                          <span class="products__price"><%= number_to_currency(product.price) %></span>
                          <button class="button button--flex products__button">
                            <i class="ri-shopping-bag-line button__icon"></i>
                          </button>
                        </div>
                      </article>
                    <% end %>
                </div>
                <div class= "load-more mt-4">
                  <%= link_to "Load more", products_path , class: "btn loadbtn btn-lg button button--flex" %>
                </div>
            </section>
          </div>

        </main>

        <!--=============== SCROLL UP ===============-->
        <a href="#" class="scrollup" id="scroll-up">
            <i class="ri-arrow-up-s-line scrollup__icon"></i>
        </a>
        <!--=============== SCROLL REVEAL ===============-->
        <script src="https://unpkg.com/scrollreveal"></script>
        <!--=============== MAIN JS ===============-->
        <script src="assets/js/main.js"></script>

<style>
.products__container {
  gap: 6rem 15rem;
}

</style>

app/views/products/index.html.erb
<section class="products section" id="products">
  <h2 class="section__title section__title-gradient products__line">
    Products
  </h2>
</section>

<div class="footer__content" id="searchbar">
  <%= form_tag products_path, :method => 'get', class: "footer__form" do %>
    <%= text_field_tag :search, params[:search], class: "footer__input", placeholder: "Search Products" %>
    <%= submit_tag "Search", class: 'button button--flex' %>
  <% end %>
</div>

<br>

<div class="product-section">
  <section class="products section" id="products">
    <div class="footer__content" id="searchbar">
      <div class="products__container container grid">
        <% @products.each do |product| %>
          <article class="products__card">
            <div class="products__content">
              <%= link_to product_path(product) do %>
                <%= cl_image_tag product.photo.key, width: 400, height: 300,crop: :pad, class:"card-img-top; products__img", alt:"Product image", id: "user_prodc" %>
              <% end %>
              <h3 class="products__title"><%= product.name %></h3>
              <span class="products__price"><%= number_to_currency(product.price) %></span>
              <button class="button button--flex products__button">
                <i class="ri-shopping-bag-line button__icon"></i>
              </button>
            </div>
          </article>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->

<div class="card-product" style="margin: 0 20%;">
  <%= cl_image_tag @product.photo.key, crop: :fill, class:"product-img", alt:"Product image"%>
  <div class="card-product-infos">
    <div>
      <h5> <%= @product.name %> </h5>
      <p><%= @product.description %></p>
      <p>Average Rating: <strong> <%= @product.average_rating.present? ? @product.average_rating : 'N/A' %></strong></p>
    </div>
    <div class="card-product-profile-price">
      <% if @product.user %>
        <%= link_to user_path(@product.user) do %>
          <% if @product.user.photo.attached? %>
            <%= cl_image_tag(@product.user.photo.key, crop: :fill, alt:"Product image", style:"max-width: 100px; max-height: 100px; margin-bottom: 10px;", class: "user-image") %>
            <style>
              .user-image {
                border-radius: 50%;
                object-fit: cover;
                height: 50px;
                width: 50px;
              }
            </style>
          <% else %>
            <%= image_tag "https://st.depositphotos.com/2218212/2938/i/600/depositphotos_29387653-stock-photo-facebook-profile.jpg", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", 'aria-expanded': false, style:"max-width: 100px; max-height: 100px; margin-bottom: 10px;" %>
            <style>
              img {
                border-radius: 50%;
                object-fit: cover;
                height: 50px;
                width: 50px;
              }
            </style>
          <% end %>
        <% end %>
      <% end %>
      <h5><%= @product.price %> €/day</h5>
    </div>
  </div>
</div>

<p></p>
<p></p>
<p></p>

<section class="section__title section__title-gradient products__line" style="background-image: linear-gradient(180deg, rgba(162,159,249,1) 0%, rgba(130,141,255,1) 0%, rgba(131,79,218,1) 100%);">
  <h2>Book Dates</h2>
</section>

  <% if @bookings.any? %>
<section class="section__title section__title-gradient products__line" style="background-image: linear-gradient(180deg, rgba(162,159,249,1) 0%, rgba(130,141,255,1) 0%, rgba(131,79,218,1) 100%);">
  <h4>Future Bookings</h4>
</section>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
    <% @bookings.order(start_date: :asc).each do |booking| %>
  <p></p>
  <div class="bookings" style="margin: 0 25%;">
    <% if booking.user.photo.attached? %>
      <%= link_to cl_image_tag(booking.user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", 'aria-expanded': false, style:"max-width: 100px; max-height: 100px; margin-bottom: 10px;"), user_path(booking.user) %>
    <% else %>
      <%= link_to image_tag("https://st.depositphotos.com/2218212/2938/i/600/depositphotos_29387653-stock-photo-facebook-profile.jpg", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", 'aria-expanded': false, style:"max-width: 100px; max-height: 100px; margin-bottom: 10px;"), user_path(booking.user) %>
    <% end %>
  <div class="bookings-content">
    <p><small><%= link_to booking.user.email.split('@').first, user_path(booking.user) %></small></p>
  </div>

  <div class="bookings-actions" style="margin: 0 20%;">
    <p>Start date: <strong><%= booking.start_date.strftime("%B %d, %Y") %></strong></p>
    <p>End date: <strong><%= booking.end_date.strftime("%B %d, %Y") %></strong></p>
  </div>
</div>
  <% end %>
  <% else %>
    <p>No Bookings yet for this Product</p>
<% end %>

<% if @product.user != current_user %>

  <% if user_signed_in? %>
    <%= form_for [@product, @booking], url: product_bookings_path(@product) do |f| %>
      <% if @booking.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
          <ul>
            <% @booking.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
<p></p>

<div class="form-group" style="margin: 0 20%;">
        <%= f.label :start_date %>
        <%= f.date_field :start_date, class: "form-control" %>
      </div>
      <p> </p>
      <div class="form-group" style="margin: 0 20%;">
        <%= f.label :end_date %>
        <%= f.date_field :end_date, class: "form-control" %>
      </div>
      <p> </p>
      <div style="margin: 20px 20%; display: flex; justify-content: center;">
        <%= f.submit "Book", class: 'button button--flex'  %>
      </div>


    <% end %>
  <% elsif current_user == @product.user %>
    <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-primary" %>
    <%= link_to "Delete this product", product_path(@product), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
  <% end %>
<% end %>
<p> </p>

<section class="section__title section__title-gradient products__line" style="background-image: linear-gradient(180deg, rgba(162,159,249,1) 0%, rgba(130,141,255,1) 0%, rgba(131,79,218,1) 100%);">
  <h2>Reviews</h2>
</section>

<div class="reviews" style="margin: 0 15%;">

<% if current_user != @product.user %>
    <% if @product.bookings.any? { |booking| booking.user == current_user && booking.end_date < Date.today } %>
      <% unless @product.reviews.exists?(user_id: current_user.id) %>
        <%= render 'reviews/form', review: @review = Review.new %>
      <% end %>
    <% elsif @product.bookings.any? { |booking| booking.user == current_user && booking.end_date >= Date.today } %>
      <% @booking = @product.bookings.where(user_id: current_user.id, status: 'approved') %>
        <p>You can review this product after the end of your Booking.</p>
    <% else %>
      <p>You need to book this product before you can review it.</p>
    <% end %>
<% end %>
<p> </p>

<% if @product.reviews.any? %>
  <% @product.reviews.order(created_at: :asc).each do |review| %>
    <div class="card mb-3" style="border-radius: 20px;">
      <div class="card-body">
        <div class="row">
          <div class="col-3">
            <p><strong>User:</strong></p>
            <p><%= review.user.email.split('@').first %></p>
          </div>
          <div class="col-3">
            <p><strong>Rating:</strong></p>
            <p><%= review.rating %></p>
          </div>
          <div class="col-6">
            <p><strong>Comment:</strong></p>
            <p><%= review.comment %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <p><strong>Review date:</strong></p>
            <p><%= review.created_at.strftime("%B %d, %Y") %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p>No reviews yet for this Product.</p>
<% end %>
</div>

<style>
  .card-product {
  overflow: hidden;
  background: #363A4E;
  box-shadow: 0 0 15px rgba(0,0,0,0.2);
  border-radius: 20px;

}

.card-product > img {
  height: 200px;
  width: 100%;
  object-fit: cover;
}

.card-product h2 {
  font-size: 16px;
  font-weight: bold;
  margin: 0;
  color: white;
}

.card-product p {
  font-size: 12px;
  opacity: .7;
  margin: 0;
  color: white;
}

.card-product .card-product-infos {
  padding: 16px;
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  position: relative;
}

.card-product-infos .card-product-user {
  position: absolute;
  right: 16px;
  top: -20px;
  width: 40px;
}
.card-product .card-product-infos div{
 position:relative;
 top:-8px;
}

/* Card product profile price */
.card-product .card-product-infos .card-product-profile-price{
 top:4px;
 display:inline-block;
 transform:translatex(0px) translatey(0px) !important;
}

/* Image */
.card-product-profile-price a img{
 position:relative;
 right:-29px;
}

/* Division */
.card-product .card-product-infos div{
 padding-top:0px;
 padding-bottom:10px;
 padding-right:0px;
}

/* Product img */
.card-product .product-img{
 height:400px;
 width:900px !important;
}

.bookings {
  display: flex;
  align-items: center;
  margin-bottom: 8px;
  background: #363A4E;
  padding: 8px 16px;
  box-shadow: 0 0 15px rgba(0,0,0,0.2);
  border-radius: 20px;
}

.bookings .bookings-content {
  flex-grow: 1;
  padding: 0 24px;
  color: white;
}

.bookings p {
  margin: 0;
  line-height: 1.4;
}

.bookings small {
  color: #ccc;
  font-weight: bold;
}

.bookings:hover .bookings-content {
  color: #ccc;
}

/* Heading */
h2{
 position:relative;
 transform:translatex(0px) translatey(0px);
 text-align:center;
}

/* Heading */
h3{
 text-align:center;
}

/* Paragraph */
.bookings .bookings-actions p{
 position:relative;
 left:127px;
 bottom:0px;
 top:0px;
}

/* Navbar Unknowndown */
#navbarDropdown{
 display:inline-block;
 transform:translatex(0px) translatey(0px) !important;
 position:relative;
 top:6px;
 left:6px;
}

/* Link */
.bookings p a{
 position:relative;
 top:4px;
 font-size:20px;
}

body {
  background-color: #24273A;
  padding-top: 100px;
}

/* New booking */
#new_booking{
 position:relative;
 top:8px;
}

/* Column 6/12 */
.card-body .col-6{
 transform:translatex(149px) translatey(0px);
  border-radius: 20px;
}

/* Card body */
.reviews .card .card-body{
 column-count:2;
 display:inline-block;
 transform:translatex(0px) translatey(0px);
}

/* Column 3/12 */
.card-body .col-3{
 transform:translatex(102px) translatey(-3px);
}

.card {
  background-color: #363A4D;
}

.card-body {
  color: white;
  border-radius: 20px;
}

.card-body strong {
  font-weight: bold;
}

/* Paragraph */
.card .card-body .row .col-3 p{
 text-align:center;
}

/* Paragraph */
.card .card-body .row .col-6 p{
 text-align:center;
}

/* Paragraph */
.card-product-infos div p{
 font-size:14px;
}

/* Heading */
.card-product-infos div h5{
 font-size:25px;
 position:relative;
 top:-6px !important;
 transform:translatex(0px) translatey(0px);
}

/* Heading */
.card-product-infos .card-product-profile-price h5{
 transform:translatex(0px) translatey(0px);
 top:4px !important;
 left:-1px;
 font-size:23px;
}

/* Division */
.card-product .card-product-infos div{
 top:0px !important;
}

/* Card product infos */
.card-product .card-product-infos{
 height:140px;
 overflow:visible;
}

/* Heading */
.card-product .card-product-infos .card-product-profile-price h5{
 bottom:auto !important;
}

/* User image */
.card-product-profile-price a .user-image{
 left:28px;
 top:5px;
}

/* User image */
.card-product .card-product-infos .card-product-profile-price a .user-image{
 right:auto !important;
}

/* Strong Tag */
.card-body .row .col-6 p strong{
 position:relative;
 top:0px;
}

/* Paragraph */
p{
 text-align:center;
}

/* Paragraph */
.card-product-infos div p{
 text-align:left;
}

/* Booking start date */
#booking_start_date{
 border-top-left-radius:20px;
 border-top-right-radius:20px;
 border-bottom-left-radius:20px;
 border-bottom-right-radius:20px;
}

/* Booking end date */
#booking_end_date{
 border-top-left-radius:20px;
 border-top-right-radius:20px;
 border-bottom-left-radius:20px;
 border-bottom-right-radius:20px;
}

/* Label */
#new_booking .form-group label{
 position:relative;
 left:30px;
}

/* Strong Tag */
.card-body .row .col-6 p strong{
 top:-2px !important;
}

/* Strong Tag */
.reviews .card .card-body .row .col-6 p strong{
 bottom:auto !important;
}

/* Paragraph */
.card-body .col-6 p{
 position:relative;
 top:-1px;
}

/* Product img */
.card-product .product-img{
 border-top-left-radius:0%;
 border-top-right-radius:0%;
 border-bottom-left-radius:0%;
 border-bottom-right-radius:0%;
 display:inline-block;
 transform:translatex(0px) translatey(0px) !important;
 position:relative;
 top:-4px;
}

app/views/shared/_navbar.html.erb
        <header class="header" id="header">
            <nav class="nav container">
                <a href="/" class="nav__logo">
                    <img src="https://i.imgur.com/CnIFUBR.png" alt="Logo">
                </a>
    <div class="nav__menu" id="nav-menu">
      <ul class="nav__list">
        <li class="nav__item">
          <%= link_to "New Product", new_product_path, class: "nav__link" %>
        </li>
        <li class="nav__item">
          <%= link_to "Gaming PC's", products_path(product_type: "Gaming PC"), class: "nav__link" %>
        </li>
        <li class="nav__item">
          <%= link_to "Consoles", products_path(product_type: "Consoles"), class: "nav__link" %>
        </li>
        <li class="nav__item">
          <%= link_to "Games", products_path(product_type: "Games"), class: "nav__link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav__item dropdown">
            <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <style>
            .avatar {
              height: 70px;
              width: 70px;
              object-fit: cover;
            }
            </style>
            <% else %>
             <%= image_tag "https://st.depositphotos.com/2218212/2938/i/600/depositphotos_29387653-stock-photo-facebook-profile.jpg", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
             <style>
            .avatar {
              height: 70px;
              width: 70px;
              object-fit: cover;
            }
            </style>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
                          <div class="nav__close" id="nav-close">
                        <i class="ri-close-line"></i>
                    </div>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="ri-function-line"></i>
                </div>
            </nav>
        </header>
    </div>
  </div>
</nav>